---
version: "3.3"
networks:
  traefik:
    external: true
  mysitebackend: null
services:
  mysitewordpress:
    build:
      context: ./wordpress
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      WORDPRESS_DB_HOST: mysitedb:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./wordpress/data:/var/www/html
    networks:
      - traefik
      - mysitebackend
    depends_on:
      - mysitedb
      - mysiteredis
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.wordpressmysite.rule=Host(`${DOMAINE}`)
      - traefik.http.routers.wordpressmysite.entrypoints=web
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.wordpressmysite.middlewares=redirect-to-https@docker
      - traefik.http.routers.wordpressmysite-secured.rule=Host(`${DOMAINE}`)
      - traefik.http.routers.wordpressmysite-secured.entrypoints=websecure
      - traefik.http.routers.wordpressmysite-secured.tls=true
      - traefik.http.routers.wordpressmysite-secured.tls.certresolver=letsencrypt
      - traefik.http.routers.wordpressmysite-secured.service=dp-web
  mysitedb:
    image: mysql:5.7
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - mysitebackend
  mysiteredis:
    image: redis:6
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 6379:6379
    networks:
      - mysitebackend
    entrypoint: redis-server --maxmemory 512mb -maxmemory-policy allkeys-lru
  mysitephpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
      - mysitebackend
      - traefik
    depends_on:
      - mysitedb
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: "3"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - /sessions
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.phpmyadminmysite.rule=Host(`${PHPMYADMIN_DOMAIN}`)
      - traefik.http.routers.phpmyadminmysite.entrypoints=web
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.phpmyadminmysite.middlewares=redirect-to-https@docker
      - traefik.http.routers.phpmyadminmysite-secured.rule=Host(`${PHPMYADMIN_DOMAIN}`)
      - traefik.http.routers.phpmyadminmysite-secured.entrypoints=websecure
      - traefik.http.routers.phpmyadminmysite-secured.tls=true
      - traefik.http.routers.phpmyadminmysite-secured.tls.certresolver=myhttpchallenge
      - traefik.docker.network=traefik
